FROM --platform=linux/amd64 python:3.11-slim

# Install system dependencies
RUN apt-get update && apt-get install -y \
    libcairo2 \
    libcairo2-dev \
    pkg-config \
    python3-dev \
    gcc \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /keyed

# Copy package files
COPY src/  ./src/
COPY tests/ ./tests/
COPY pyproject.toml ./

# Install the package
RUN pip install --no-cache-dir ".[test]"

# Run tests
RUN pytest tests/
