name: keyed
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python<3.13,>=3.11
  - ffmpeg
  - cairo
  - pycairo
  - pango>=1.56.0
  - librsvg
  - pip
  - pip:
    - -e ".[all]"
    - -e "../keyed-extras"
