site_name: Keyed
site_url: https://dougmercer.github.io/keyed
repo_url: https://github.com/dougmercer/keyed

theme:
  name: material
  custom_dir: docs/overrides
  palette:
  - media: "(prefers-color-scheme)"
    toggle:
      icon: material/lightbulb-auto
      name: Switch to light mode
  - media: '(prefers-color-scheme: light)'
    scheme: default
    primary: teal
    accent: amber
    toggle:
      icon: material/lightbulb
      name: Switch to dark mode
  - media: '(prefers-color-scheme: dark)'
    scheme: slate
    primary: teal
    accent: amber
    toggle:
      icon: material/lightbulb-outline
      name: Switch to system preference
  features:
    - announce.dismiss
    - content.code.annotate
    - content.code.copy
    - content.code.select
    # - content.footnote.tooltips
    - content.tooltips
    - content.tabs.link
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.preview
    - navigation.instant.progress
    - navigation.path
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  # - tables
  - toc:
      permalink: true
  # - pymdownx.arithmatex:
  #     generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  # - pymdownx.magiclink:
  #     normalize_issue_symbols: true
  #     repo_url_shorthand: true
  #     user: dougmercer
  #     repo: keyed
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

  # pymdownx blocks
  - pymdownx.blocks.admonition:
      types:
        - note
        - attention
        - caution
        - danger
        - error
        - tip
        - hint
        - warning
        # Custom types
        - info
        - check
  - pymdownx.blocks.details
  - pymdownx.blocks.tab:
      alternate_style: True
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Home: index.md
  - Install: install.md
  - Tutorial:
    - First Scene: tutorial/first_scene.md
    - Easing: tutorial/easing.md
    - Transformations: tutorial/transformations.md
    - Reactivity and Animation: tutorial/animation.md
  - API Reference:
    - Animation: api/animation.md
    - Easing: api/easing.md
    - Transformations: api/transforms.md
    - Shapes, Lines, and Curves: api/shapes.md
    - Core: api/core.md
    - Text: api/text.md
    - Scene: api/scene.md
    - Compositor: api/compositor.md
    - Colors: api/colors.md
    - Effects: api/effects.md
    - Annotations: api/annotations.md
    - Utilities: api/utils.md
    - Implementation Details: api/impl.md
  - Gallery:
    - Gallery: gallery/index.md
    - Bouncing Bowl: gallery/first_scene.md
    - Code Animation: gallery/code_replace_complex.md
    - Color Interpolation: gallery/color_interp.md
    - Code Highlighting: gallery/curve_interp.md
    - Plotting: gallery/plot_with_axis.md
    - Bezier Explainer: gallery/bezier_explainer.md
  - Contributing:
    - Contributing: contributing/index.md
    - Dev Environment: contributing/environment.md
  - Changelog: changelog/index.md
  - Keyed Extras:
    - Keyed Extras: extras/index.md
    - Features & Goals: extras/goals.md
    - Fair Use Policy: extras/fairuse.md
    - Keyed Extras: https://dougmercer.github.io/keyed-extras-docs/

hooks:
  - docs/hooks/video_replace.py
  - docs/hooks/shortcodes.py

plugins:
  - search
  - autorefs
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src]
          inventories:
          - https://dougmercer.github.io/keyed-extras-docs/objects.inv
          - https://dougmercer.github.io/signified/objects.inv
          - https://shapely.readthedocs.io/en/latest/objects.inv
          - https://docs.python.org/3/objects.inv
          - https://pycairo.readthedocs.io/en/latest/objects.inv
          - https://numpy.org/doc/stable/objects.inv
          - https://pygments.org/objects.inv
          options:
            docstring_style: google
            docstring_options:
              show_if_no_docstring: true
            inherited_members: true
            members_order: source
            filters:
            - '!^_'
            separate_signature: true
            signature_crossrefs: true
            show_symbol_type_toc: true
            show_symbol_type_heading: true
            show_root_heading: true
            show_source: true
            extensions:
              - docs/plugins/custom_tags_extension.py

extra_css:
  - stylesheets/extra.css
