name: 'Install System Dependencies'
description: 'Install required system dependencies for the project'
runs:
  using: "composite"
  steps:
    - name: Cache apt packages
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: libcairo2-dev pkg-config python3-dev ffmpeg
        version: 1.0
