name: Documentation

on:
  push:
    branches: [main]
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build-deploy-docs:
    if: github.event_name == 'release' || (github.event_name == 'push' && github.ref == 'refs/heads/main')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: 'pip'
          cache-dependency-path: '**/pyproject.toml'
      - uses: ./.github/actions/install-system-deps
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ".[docs,previewer]"
      - name: Generate example animations
        run: bash ./docs_src/generate_docs.sh
      - run: mkdocs gh-deploy --force
