name: Documentation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [published]

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcairo2-dev pkg-config python3-dev ffmpeg
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ".[docs,previewer]"
          
      - name: Generate example animations
        run: bash ./docs_src/generate_docs.sh

      - name: Build documentation
        run: mkdocs build
        
      - name: Upload documentation artifact
        uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: site/
          
  deploy-docs:
    runs-on: ubuntu-latest
    needs: build-docs
    if: github.event_name == 'release' || (github.event_name == 'push' && github.ref == 'refs/heads/main')
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          
      - name: Install MkDocs
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material mkdocstrings[python] mkdocs-material-extensions
          
      - name: Download built documentation
        uses: actions/download-artifact@v4
        with:
          name: documentation
          path: site/
          
      - name: Deploy to GitHub Pages
        run: |
          mkdocs gh-deploy --force --config-file mkdocs.yml
