name: Type Checking

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  type-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: 'pip'
          cache-dependency-path: '**/pyproject.toml'
      - uses: ./.github/actions/install-system-deps
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ".[lint,previewer]"
      - name: Run Pyright
        uses: jakebailey/pyright-action@v2
        with:
          pylance-version: latest-release
          extra-args: "src/"
